In [14]:
# a. [30] 1~100 까지 integer random number가 들어 있는 3x10x10 배열을 만들고 결과를 화면에 출력하십시오.
import numpy as np
arr = np.random.randint(1, 101, size=(3, 10, 10))
print(arr)

[[[ 29  57  72  55  69  87  96  73   8  95]
  [ 11  26   9  79  68  52 100  51   8  56]
  [ 39   9  34  96  21  63  91   6  82  42]
  [ 10  91  56  32  64  51  52  80  61  53]
  [ 18  49 100  15  15  64  89  73  97  48]
  [ 44  27  15  66  47   7  85  18  76  36]
  [ 30   9  56  34  44  25  14  64  13  92]
  [ 56  17   9  63  65  53  30  30  85  33]
  [ 47  50  34  92  78  83  70  63  68  48]
  [ 12  47  71  29  74  88  45  31  13  53]]

 [[ 73  59  15  59  40  20  32  16  91  23]
  [  4  16   3  98  83  19 100  92 100  67]
  [ 80   7  72  54  31   9  99  73  24  18]
  [ 85  72  83  41   3  14   2  58  73  69]
  [ 35  81  36  84  68   9  22  69  54  38]
  [ 94  14  18  50  15  95  10  28  93  13]
  [ 51  70  55  80  83  32  59  53  40  61]
  [  9  14  59  74   3   4  60  97  18  72]
  [ 66  79  82  65  30  97  30  24  83  78]
  [100  10  20  20  63   6  69  91  45  26]]

 [[100   9   7  72  38  71  73  48  11  17]
  [ 14 100  92  37  62  44  98  36  61  52]
  [ 89  72  62  36 100  57  17  27  60  80]
  [ 22  24  18  68  81  73  20  44  31  12]
  [ 66  43  19  80  81  75  37  27  47  73]
  [ 27  36  13  93  62  36  12  66  59  40]
  [ 63  29  73  89  77  27  86  45  95  89]
  [ 57  86 100  20  92  42  96  62  69  67]
  [ 19  19  64  40  68  72  35  61  11  87]
  [ 58  17   8  16  14  32  50  89  57  70]]]

In [15]:
# b. [35] 50보다 크거나 같은 값은 1, 50보단 작은 값은 2로 변환한 결과를 화면에 출력하십시오.
new_arr = np.where(arr >= 50, 1, 2)
print(new_arr)

[[[2 1 1 1 1 1 1 1 2 1]
  [2 2 2 1 1 1 1 1 2 1]
  [2 2 2 1 2 1 1 2 1 2]
  [2 1 1 2 1 1 1 1 1 1]
  [2 2 1 2 2 1 1 1 1 2]
  [2 2 2 1 2 2 1 2 1 2]
  [2 2 1 2 2 2 2 1 2 1]
  [1 2 2 1 1 1 2 2 1 2]
  [2 1 2 1 1 1 1 1 1 2]
  [2 2 1 2 1 1 2 2 2 1]]

 [[1 1 2 1 2 2 2 2 1 2]
  [2 2 2 1 1 2 1 1 1 1]
  [1 2 1 1 2 2 1 1 2 2]
  [1 1 1 2 2 2 2 1 1 1]
  [2 1 2 1 1 2 2 1 1 2]
  [1 2 2 1 2 1 2 2 1 2]
  [1 1 1 1 1 2 1 1 2 1]
  [2 2 1 1 2 2 1 1 2 1]
  [1 1 1 1 2 1 2 2 1 1]
  [1 2 2 2 1 2 1 1 2 2]]

 [[1 2 2 1 2 1 1 2 2 2]
  [2 1 1 2 1 2 1 2 1 1]
  [1 1 1 2 1 1 2 2 1 1]
  [2 2 2 1 1 1 2 2 2 2]
  [1 2 2 1 1 1 2 2 2 1]
  [2 2 2 1 1 2 2 1 1 2]
  [1 2 1 1 1 2 1 2 1 1]
  [1 1 1 2 1 2 1 1 1 1]
  [2 2 1 2 1 1 2 1 2 1]
  [1 2 2 2 2 2 1 1 1 1]]]

In [19]:
# c. [35] 1번째 배열에서 아래 그림에서와 같이 붉은색 상자 안의 원소들을 추출하여 화면에 출력하십시오.
# 여기서, 배열 index는 0부터 시작하여, 0, 1, 2입니다.

new_arr2 = arr[1, -5:, -5:] # 처음 만든(a에서) 배열에서 가져오기
print(new_arr2)

new_arr3 = new_arr[1, -5:, -5:] # 1,2로 변환시킨 배열에서 가져오기
print(new_arr3)

[[95 10 28 93 13]
 [32 59 53 40 61]
 [ 4 60 97 18 72]
 [97 30 24 83 78]
 [ 6 69 91 45 26]]
[[1 2 2 1 2]
 [2 1 1 2 1]
 [2 1 1 2 1]
 [1 2 2 1 1]
 [2 1 1 2 2]]